# Generated by Django 4.2.3 on 2023-08-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task1',
            name='is_completed',
            field=models.BooleanField(),
        ),
    ]
