# Generated by Django 4.2.3 on 2023-08-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_alter_task1_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task1',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
