# Generated by Django 4.2.3 on 2023-08-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_alter_userregistration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
