# Generated by Django 4.2.3 on 2023-08-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_alter_userregistration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task1',
            name='is_completed',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=0),
        ),
    ]
